require "bungee.options"
require "bungee.key-mappings"
require "bungee.lsp"
require "bungee.plugins.plugins"
require "bungee.plugins.colorscheme"
require "bungee.plugins.cmp"
require "bungee.plugins.vim-terraform"
require "bungee.plugins.telescope"
require "bungee.plugins.treesitter"
require "bungee.plugins.autopairs"
require "bungee.plugins.comment"
require "bungee.plugins.gitsigns"
require "bungee.plugins.fugitive"
require "bungee.plugins.illuminate"
require "bungee.plugins.nvim-tree"
require "bungee.plugins.nvim-surround"
require "bungee.plugins.focus"
require "bungee.plugins.whichkey"
-- require "bungee.plugins.neo-zoom"

-- require "user.options"
-- require "user.keymaps"
-- require "user.plugins"
-- require "user.colorscheme"
-- require "user.cmp"
-- require "user.lsp"
-- require "user.telescope"
-- require "user.treesitter"
-- require "user.gitsigns"
-- require "user.autopairs"
-- require "user.comment"

-- require "user.nvim-tree"
-- require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
-- require "user.whichkey"
require "user.autocommands"
