require "bungee.options"
require "bungee.key-mappings"
require "bungee.lsp"
require "bungee.packer"
require "bungee.plugins.alpha"
require "bungee.plugins.autocommands"
require "bungee.plugins.autopairs"
require "bungee.plugins.colorscheme"
require "bungee.plugins.cmp"
require "bungee.plugins.comment"
require "bungee.plugins.gitsigns"
require "bungee.plugins.fugitive"
require "bungee.plugins.illuminate"
require "bungee.plugins.impatient"
require "bungee.plugins.indentline"
require "bungee.plugins.lualine"
require "bungee.plugins.nvim-surround"
require "bungee.plugins.nvim-tree"
require "bungee.plugins.shade"
require "bungee.plugins.telescope"
require "bungee.plugins.toggleterm"
require "bungee.plugins.treesitter"
require "bungee.plugins.project"
require "bungee.plugins.vim-terraform"
require "bungee.plugins.whichkey"
-- require "bungee.plugins.neo-zoom"

